CHANGELOG.md
src/components/Button/Button.js
src/components/Button/Button.scss
src/components/Editor/NewComponentButton/NewComponentButton.js
src/editor-spacing.scss

- Refactors the button component to accept a buttonOuter prop
- Removed the theme from the NewComponentButton as pulls styles from the app class
- Styling for the small button, with larger hit area
-----
To use the `btn--small` in the future just need to pass the `buttonOuter` to the `Button` and `btn--small` class
-----
Video as no review app:
https://user-images.githubusercontent.com/14238047/209164727-63b36ed7-754f-4d1d-8d80-b240cb63f9f7.mov

Small buttons

---

CHANGELOG.md
package.json

- Styling of the projects list (#317)
- Ability to collapse and expand the left hand file pane (#316)
- Plausible event tracking for left hand file pane (#325)
- Last updated field added to the projects table (#319)
- Message for empty state on projects (#327)
- Rename project action on project index page (#324)
- Context menu for project index page actions on mobile (#324)
- Danger button styling (#330)
- Change port number to fix 'no consent token' error (#326)
- Long file names truncated rather than scrolling in left hand file pane (#316, #337)
- Tab scrollbars only appear when necessary (#331)
- Added merge=union gitattribute for this file (#339)
- Make sure button text is always centered (#328)
- Make theme and font size persist across all pages of the app (#329)
- Make dismissing …

Release v0.11.0

---

CHANGELOG.md
package.json

- Simplified the URL structure to replace project type (#347)
- Upgrade `react-router` to `v6`
- Bump json5 from 1.0.1 to 1.0.2 (#321)
- Show `p5` error messages in the user interface (#346)
- Get review apps working (#351)

release for v0.12.0

---

CHANGELOG.md
README.md

- Added release notes in `README.md`

Adding release notes to README

---

CHANGELOG.md
src/components/Editor/EditorPanel/EditorPanel.js

- Adds a `visibility: hidden` to the hidden img tag from code mirror to stop the alt text showing in the editor
Before: 
After:

Fix null from the hidden codemirror img

---

CHANGELOG.md
src/tabs.scss

After increasing the hit area on the output toggle there is now a 2px difference between the heights of the tab container. Have added a `height: 50px` so that they stay the same height of `51px` (50px + 1px border)
**The bug:** 
See bug on staging: https://staging-editor.raspberrypi.org/ 
The text input is `49px` and the output is `51px`

Tab discrepancy fix

---

CHANGELOG.md
package.json
src/components/AppRoutes.js
src/index.js
src/sentry.js
yarn.lock

I've refactored our Sentry integration to follow the guides for
* [Event propagation](https://docs.sentry.io/platforms/javascript/guides/react/performance/instrumentation/automatic-instrumentation/#enable-instrumentation)
* [Router integration](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/#usage-with-routes--component)
* [GraphQL link](https://github.com/DiederikvandenB/apollo-link-sentry)
The routing integration means that the events in Sentry have the URL params substituted:
The propagation config change gives us distributed tracing to other apps, e.g. editor-api

Add sentry tracing for GraphQL and Routing

---

CHANGELOG.md
storybook/.storybook/main.js
storybook/yarn.lock

Removes the "@storybook/addon-links" from the addons list (since it's not defined in the package.json it won't work, and isn't used)

Remove unused package from addons

---

CHANGELOG.md
src/App.scss
src/components/Editor/Runners/PythonRunner/OutputViewToggle.scss

Minor updates to styles to fix:
- Button width
- Order on svg when selected
Both of which cause the editor to look like this in Safari

Minor fixes (mostly buttons) to resolve issues in safari

---

CHANGELOG.md
package.json

- Error capturing for python project fires to editor-api rather than Sentry (#625)

0.18.2 Release

---

src/i18n.js

"Log in" is the correct spelling when used as a verb, eg. here:

Correct typo; login -> log in

---

CHANGELOG.md
src/components/WebComponentProject/WebComponentProject.jsx
src/components/WebComponentProject/WebComponentProject.test.js
src/events/WebComponentCustomEvents.js
src/web-component.html

- Moved web component custom events from the `editor-wc` element to the `document`, mainly to make it easier to test
- Namespaced custom events to be prefixed with `editor-`, so host page knows the event has come from the editor web component
- Slight refactor of the `WebComponentProject`, mostly to make it more testable
- Added tests for the `WebComponentProject`

Web component events refactor and testing

---

CHANGELOG.md
src/components/Login/LoginMenu.jsx
src/components/Login/LogoutButton.jsx
src/components/Login/LogoutButton.test.js
src/utils/userManager.js

Related to #714 
Hits signoutRedirect with a `id_token` during logout to invalidate hydra session
This requires `post_logout_redirect_uris` to be registered with hydra client before merge (currently manual but I have an influx branch to bring this into terraform)

Oidc-redux Signout Flow

---

storybook/.storybook/preview.js

Adds a toolbar item that then wraps the story in the classes needed to theme the editor in light or dark mode.
https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/0d825ee6-27bd-45e2-a3b9-c209be25a8de

Allow themes to be set and toggled globally

---

CHANGELOG.md
src/assets/stylesheets/Project.scss

Related to https://github.com/RaspberryPiFoundation/editor-ui/issues/708 and fixes input/output panel breakpoints when web component is positioned on a page that doesn't take the full width of the screen
Currently the breakpoints change as a result of the positioning of the web component on the page e.g. if additional margin is added around the web component the breakpoints will be effected
https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/371ce394-6fb8-4e97-bb67-2e32e58ef4b9

set breakpoints on container not media query

---

CHANGELOG.md
README.md

Updated README to document output class for editor/projects styling

README updated

---

CHANGELOG.md
src/assets/stylesheets/Instructions.scss
src/assets/stylesheets/ProgressBar.scss
src/assets/stylesheets/Sidebar.scss

- Utilisting existing filename from `kramdown` for the code block
- Making the instructions progress bar more in line with the designs

Minor instructions styling fixes

---

CHANGELOG.md
src/components/WebComponentProject/WebComponentProject.jsx
src/containers/WebComponentLoader.jsx
src/web-component.html
src/web-component.js

Part of [#2428](https://github.com/RaspberryPiFoundation/projects-ui/issues/2428)
- css strings can be passed to the WebComponent through a `hostStyle` prop, allowing the ShadowDOM to receive styles from the host app.

Issue 2428 host styles added for web component

---

CHANGELOG.md
src/assets/stylesheets/Project.scss
src/assets/stylesheets/WebComponent.scss

Currently due to the styling changes required to maximise the height of the web component in Firefox the standalone editor took up too much space (didn't account for the top nav). This fix applies the required `min-block-size` only to the web component

Fix project height for standalone editor

---

CHANGELOG.md
src/assets/stylesheets/DesignSystemButton.scss

Fix width of new file button

---

CHANGELOG.md
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx

This PR fixes and extends the assets url/blob replacements throughout css and html:
- Allows multiple url replacements in css
- Generalises the attribute replacement and applies to `data-src` attributes too

Fix blob replacement for css and html attributes

---

CHANGELOG.md
src/web-component.js

Fix so anything other than explicitly setting the boolean attributes as false is taken as true

Fix web-component boolean attributes

---

CHANGELOG.md
src/assets/stylesheets/DownloadPanel.scss
src/components/Menus/Sidebar/DownloadPanel/DownloadPanel.jsx
src/components/Menus/Sidebar/DownloadPanel/DownloadPanel.test.js
src/components/SaveButton/SaveButton.jsx

Allows mobile users to save their project and remix in place of auto remixing (https://github.com/RaspberryPiFoundation/editor-ui/issues/843)

Added a save button to DownloadPanel

---

CHANGELOG.md
src/components/Editor/EditorPanel/EditorPanel.jsx
src/components/ExternalFiles/ExternalFiles.jsx
src/containers/WebComponentLoader.jsx
src/hooks/useProject.js
src/redux/EditorSlice.js
src/utils/apiCallHandler.js
src/web-component.html
src/web-component.js

Code and assets identifiers

---

.dockerignore
.gitignore
CHANGELOG.md
Dockerfile
docker-compose.yml

Yarn v3 needs:
- activating inside Dockerfile
- volumes need mounting in docker-compose
- `yarnrc.yml` could be different between environments (i.e. local machine and container) so ignoring the file in the repo and generating one on build in docker

Fix local docker setup to add support for yarn v3

---

CHANGELOG.md
src/assets/stylesheets/PythonRunner.scss

Fixing text output width on firefox

---

CHANGELOG.md
package.json
src/components/Button/Button.jsx
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx
src/components/Menus/Dropdown/Dropdown.jsx

Dynamically add `crossorigin` attribute to `img` tags when `src` attribute is swapped out for a backend provided image.
https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/4d362a70-6502-4c46-96ce-8f73a6f4583b

Add crossorigin attribute to img tags in html iframe

---

CHANGELOG.md
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx
src/utils/externalLinkHelper.js

As part of project migration from trinket to the code editor some additional functionality is required. This PR enables iframes to be used from the same approved external sources list as used for href's and other src attributes. By expanding this to allow for self references (i.e. src with a value the same as the `PUBLIC_URL`) users can embed other projects they (or we) own in iframes into their projects

Enable allowed external iframe src's

---

CHANGELOG.md
src/components/WebComponentProject/WebComponentProject.integration.test.js
src/components/WebComponentProject/WebComponentProject.jsx
src/events/WebComponentCustomEvents.js

See [this issue][1].
The integrated version of the editor in `editor-ui` redirects to the new project identifier URL after a project is remixed. However, the `editor-standalone` version which uses the editor web component was unable to detect changes in the project identifier and so the redirect was not working.
I've addressed this by making a new custom event ("editor-projectIdentifierChanged") available from the web component with the idea that we'll add an event listener in `ProjectComponentLoader` which redirects to the remixed project identifier URL (see https://github.com/RaspberryPiFoundation/editor-standalone/pull/63). The custom event is not dispatched when the project identifier is not set, because that's not currently useful in `editor-standalone`, but it would be easy enough …

Dispatch event when project identifier changes

---

CHANGELOG.md
package.json

This script is broken, because no `.prettierrc` file is included in the repo.
We're relying on the `prettier` plugin for `eslint` to do code formatting & checking, e.g. in `.github/workflows/ci-cd.yml` where we [invoke `yarn lint`][1] to check the formatting.
Similarly, the `lint:fix` script can be used to apply formatting. So the `format` script is redundant and potentially confusing to new developers.
[1]: https://github.com/RaspberryPiFoundation/editor-ui/blob/5197facfc6253be548205d24e89478af286eb384/.github/workflows/ci-cd.yml#L31-L32

Remove broken `format` script

---

CHANGELOG.md
src/redux/EditorSlice.js
src/redux/EditorSlice.test.js

This fixes [an issue](https://github.com/RaspberryPiFoundation/editor-ui/issues/1001) which you can see if you follow these steps:
1. Login
2. Visit a project you do not own
3. Edit the code
4. Save the project (thus remixing it)
5. Visit the original project URL again
6. See your changes in the code when you should see the original version
This was happening because after step 3 the auto-save functionality stored the project (with your code changes) in local storage against the original project identifier. When the project was saved, the remixed version was created in the database, but the cached version was left in local storage. When you re-visit the original project URL, the project cached in local storage was loaded, because the URL path matches the local storage key, i.e. the …

Invalidate cached project when project is remixed

---

CHANGELOG.md
README.md
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js
src/redux/EditorSlice.js
src/redux/EditorSlice.test.js
src/web-component.js

This work came out of [this issue][1].
These changes mean that it is now possible to configure the web component not to load a logged-in user's remixed version of the project by setting `load_remix_disabled` to `true`.
We want to use this in `editor-standalone` with the web component editor so that we reproduce the behaviour currently in `editor-ui` with the integrated editor.
When the new attribute is set to `true`, the `loadRemix` property passed to `useProject` in `WebComponentLoader` is forced to be `false` so that the remixed version of the project will not be loaded.
The name of the new attribute isn't ideal - I would rather have used `load_remix_enabled` - however, boolean attributes of the web component default to `false` and I want the default behaviour to remain unchanged to …

Add `load-remix-enabled` attribute to web component

---

CHANGELOG.md
package.json

I've grouped the unreleased changelog items into "Added", "Changed" & "Fixed" - I'm fairly confident that what I've done makes sense, but it would be worth another pair of eyes!
I've made this a minor version bump, because it includes both new functionality added in a backwardly compatible manner and backward compatible bug fixes, but no incompatible API changes as far as I'm aware. Please let me know if the latter is incorrect!

Release v0.23.0

---

CHANGELOG.md
src/redux/EditorSlice.js
src/redux/EditorSlice.test.js

Previously when `BYPASS_AUTH` was set to `true` in `editor-api` and a remix was triggered in `editor-ui`, the editor went into an ♾️ infinite loop creating remix after remix after remix of the same project... 
This was happening, because `saveTriggered` was never being set to `false` in the "editor/remixProject/pending" case in `EditorSlice` like it is being in "editor/saveProject/pending". Thus [this condition][1] in the `useProjectPersistence` hook was always `true` and `syncProject("remix")` was repeatedly dispatched.
https://github.com/RaspberryPiFoundation/editor-ui/blob/2df8a9761bff2de4824a7815252eb62560e85356/src/redux/EditorSlice.js#L372-L375
https://github.com/RaspberryPiFoundation/editor-ui/blob/2df8a9761bff2de4824a7815252eb62560e85356/src/redux/EditorSlice.js#L397-L399
We were …

Fix infinite remix loop when BYPASS_AUTH set in editor-api

---

CHANGELOG.md
docker-compose.yml

* Avoid creating an extra unnecessary container
* Avoid a warning about the `version` property

Fixes for docker-compose.yml

---

CHANGELOG.md
README.md
src/components/Editor/Project/Project.jsx
src/components/ProjectBar/ProjectBar.jsx
src/components/ProjectName/ProjectName.jsx
src/components/ProjectName/ProjectName.test.js
src/components/WebComponentProject/WebComponentProject.jsx
src/containers/WebComponentLoader.jsx
src/web-component.js

Addresses #986 which is part of RaspberryPiFoundation/editor-standalone#16.
This will allow us to make the project name editable in `editor-standalone` (see RaspberryPiFoundation/editor-standalone#125) while leaving other projects using the web component (e.g. `projects-ui`) and the integrated version in `editor-ui` unchanged.
Note that this new attribute only affects the `ProjectName` component in the `ProjectBar` and not the one in the sidebar, i.e. in `ProjectsPanel`.

Add project_name_editable attribute to web component

---

.github/workflows/changelog.yml
.github/workflows/ci-cd.yml
.github/workflows/deploy.yml
CHANGELOG.md

Previously (e.g. in [this job run](https://github.com/RaspberryPiFoundation/editor-ui/actions/runs/9126135030) at the bottom) we were seeing a bunch of deprecation warnings like this one:
lint:
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v3,
actions/setup-node@v3.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Fix deprecation warnings in GitHub Actions

---

CHANGELOG.md
src/components/AppRoutes.jsx
src/containers/ProjectComponentLoader.jsx

As far as we can tell, this route is [no longer used anywhere][1].
This was originally added in Mar 2022 in #72 for the "ESA demo". I suspect we now achieve a similar effect by using the web component with [its `embedded` attribute](https://github.com/RaspberryPiFoundation/editor-ui/blob/340ab1192fb3358ad4614034208603948f8b95d6/src/web-component.js#L50) set to `true`, rather than using an `iframe` with its `src` set to this route.
I found it confusing to see both the `/:locale/embed/viewer/:identifier` and this route in the `AppRoutes` component. Removing this one makes the code less confusing.
I've also removed the now redundant `embedded` property on the `ProjectComponentLoader` component and the similarly redundant call to `useEmbeddedMode` which is a no-op when `embedded` is `false`. …

Remove unused `/embedded/projects/:identifier` route

---

.github/workflows/ci-cd.yml
CHANGELOG.md
cypress.config.mjs

See individual commit notes for details:
* [Avoid repeated `URIError` in Cypress spec CI output](https://github.com/RaspberryPiFoundation/editor-ui/commit/db0225e4ec2ea460a70c7703f48f84ed945ebde1)
* [Reinstate default Cypress screenshot behaviour](https://github.com/RaspberryPiFoundation/editor-ui/commit/9beab733c90c09e6ec6be407060b1a5c1a9b8906)
* [Use `quiet` option when running Cypress specs in CI](https://github.com/RaspberryPiFoundation/editor-ui/commit/d8bfcca5f45efacb7f1a4eaa1075c6d8e00e3318)

Improvements to Cypress specs in CI

---

CHANGELOG.md
config/webpack.config.js
scripts/start.js
src/assets/stylesheets/App.scss
src/assets/stylesheets/Project.scss
src/assets/stylesheets/Sidebar.scss
webpack.component.config.js
yarn.lock

See individual commit notes for more detail:
* [Fix warning re fill-available vs stretch](https://github.com/RaspberryPiFoundation/editor-ui/commit/2e36964cc110678a0d52e18608d6e526e5846c4d)
* [Fix dev server constructor deprecation warning in start.js](https://github.com/RaspberryPiFoundation/editor-ui/commit/61ef83afa3bffba13a66d2297d5d4f1f086e5482)
* [Fix dev server listen deprecation warning in start.js](https://github.com/RaspberryPiFoundation/editor-ui/commit/1727fe4e61ed3389de73c4b03d7ff203f2772a42)
* [Don't display webpack stats on starting dev server](https://github.com/RaspberryPiFoundation/editor-ui/commit/959003aa268285746f0e88d4394c1a9a95f7b948)
* [Fix "caniuse-lite is outdated" warning](https://github.com/RaspberryPiFoundation/editor-ui/commit/36fd74dbd05213ad5c267429afd87a4bb …

Fix warnings and verbose output when starting Webpack Dev Server

---

.github/workflows/ci-cd.yml
CHANGELOG.md
cypress/e2e/spec-wc.cy.js
src/web-component.html

The `editor-standalone` app will:
* Listen for "editor-projectIdentifierChanged" custom events from the web component and will redirect to the remixed project's URL. The relevant web component behaviour was changed in #990. The relevant `editor-standalone` behaviour was changed in RaspberryPiFoundation/editor-standalone#63.
* Set the web component `load_remix_disabled` attribute to `true` so that the original project will be loaded in preference to the remixed version (unlike the way projects-ui works). The relevant web component behaviour was changed in #992 & #1003. The relevant `editor-standalone` behaviour will be changed in RaspberryPiFoundation/editor-standalone#85.
This spec checks that the web component provides the relevant behaviour for editor-standalone to use.
I did attempt to …

Add e2e spec for project remix behaviour in web component

---

CHANGELOG.md
cypress/e2e/spec-wc.cy.js
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js

Previously, even if the `authKey` property was provided and a logged-in user was stored in `localStorage`, on first render the value of `user` was `null`. This was because the `localStorageUserMiddleware` which dispatches `setUser` to store the user in Redux had not yet been triggered.
**This meant that previously if we tried to use the web component to view a project that the logged-in user owned, the request to editor-api to load the project would respond with a 403 Forbidden and the project would not load.**
I'm fairly (but not completely) sure that the assertions in the "with user set in local storage" group of examples in
`src/containers/WebComponentLoader.test.js` were incorrect, i.e. if the `authKey` is set and a `user` is present in `localStorage` we ought to load the project …

Fix initial value of `user` in `WebComponentLoader`

---

CHANGELOG.md
cypress/e2e/spec-wc.cy.js

The comment about the `authKey` needing to match `HydraPublicApiClient::BYPASS_AUTH_USER_ID` in editor-api was incorrect. While the actual value is unimportant in this spec, it seems better to make it as realistic as possible.

Make `authKey` in e2e web component spec more realistic

---

CHANGELOG.md
README.md
cypress/e2e/spec-wc-block-to-text.cy.js
src/assets/stylesheets/EmbeddedViewer.scss
src/assets/stylesheets/InternalStyles.scss
src/assets/stylesheets/PythonRunner.scss
src/assets/stylesheets/Tabs.scss
src/components/Editor/Output/Output.jsx
src/components/Editor/Output/Output.test.js
src/components/Editor/Project/Project.jsx
src/components/Editor/Runners/PythonRunner/PythonRunner.jsx
src/components/Editor/Runners/PythonRunner/PythonRunner.test.js
src/components/Editor/Runners/RunnerFactory.jsx
src/components/EmbeddedViewer/__snapshots__/EmbeddedViewer.test.js.snap
src/components/ExternalFiles/ExternalFiles.jsx
src/components/Mobile/MobileProject/MobileProject.jsx
src/components/WebComponentProject/WebComponentProject.jsx
src/components/WebComponentProject/WebComponentProject.test.js
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js
src/hooks/useProject.js
src/hooks/useProject.test.js
src/redux/EditorSlice.js
src/redux/EditorSlice.test.js
src/utils/apiCallHandler.js
src/utils/apiCallHandler.test.js
src/web-component.html
src/web-component.js

This adds a bunch of new attributes (e.g. `output_only`, `output_panels` & `assets_identifier`), methods (e.g. `rerunCode`) and behaviour to the web component to support [the Block-to-Text app](https://block-to-text-alpha.pages.dev/).
This branch is heavily based on the work in #782 which is what is what is currently being used by the alpha version of the Block-to-Text app. I've cherry-picked commits from the original work onto the latest work in`main` and curated the commits a bit to try to make them atomic and easier to follow.
In each commit:
* I've reviewed the code
* I've added unit tests
* I've fixed any bugs that I've found
* I've tried to explain the change at a high level
* I've tried to explain the motivations behind the change
Obviously writing the explanations after the fact …

Add support for Block-to-Text app

---

CHANGELOG.md
package.json

- Add `project_name_editable` attribute to web component (#1009)
- Fires custom event when the theme changes (#1015)
- Add `output_only` attribute to web component (#1019 & originally #782)
- Add `assets_identifier` attribute to web component (#1019 & originally #901)
- Enhance `code` attribute on web component to override project main component content (#1019 & originally #901)
- Add `runCode`, `stopCode` & `rerunCode` methods to web component (#1019 & originally #899)
- Send error details in "editor-runCompleted" event (#1019 & originally #915)
- Return error details to web component (#1019 & originally #915)
- Add `output_panels` attribute to web component (#1019 & originally #909)
- Remove unused `/embedded/projects/:identifier` route (#1013)
- Remove unused `REACT_APP_LOGIN_ENABLED` …

Release v0.24.0

---

CHANGELOG.md
README.md
cypress/e2e/spec-wc.cy.js
src/components/Editor/Output/Output.jsx
src/components/Editor/Output/Output.test.js
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx
src/components/Editor/Runners/HtmlRunner/HtmlRunner.test.js
src/components/WebComponentProject/WebComponentProject.jsx
src/components/WebComponentProject/WebComponentProject.test.js
src/containers/WebComponentLoader.jsx
src/web-component.js

This makes a number of changes to support the use of the web component in the embedded view of `editor-standalone`. See [this PR](https://github.com/RaspberryPiFoundation/editor-standalone/pull/164) for details.
In particular, I've tried to "tighten" up what we mean by the `isEmbedded` state (and its new corresponding `embedded` web component attribute). It's now very specifically intended to indicate that the we are in the embedded view i.e. on [the `/:locale/embed/viewer/:identifier` route](https://github.com/RaspberryPiFoundation/editor-standalone/blob/b38a307ea78ae672593befa0875fb550c9ba6689/src/components/AppRoutes.jsx#L75-L78).
In conjunction with [this block-to-text PR](https://github.com/RaspberryPiFoundation/block-to-text-alpha/pull/125), this has allowed me to remove some checks …

Support use of the web component in editor-standalone's embedded view

---

CHANGELOG.md
package.json

- Add `embedded` attribute to web component (#1030)
- Add `output_split_view` attribute to web component (#1030)
- Changes to web component behaviour to support use in embedded view in editor-standalone (#1030)
- None

Release v0.25.0

---

CHANGELOG.md
src/assets/stylesheets/Sidebar.scss
src/assets/stylesheets/Tabs.scss
src/assets/stylesheets/index.scss
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js
src/web-component.html
src/web-component.js

Adds support to use built in editor styles in web component, currently defaults to general design system colours. If the flag is true, import those styles and applies them, else falls back to design system styling.

UAT web component fixes

---

CHANGELOG.md
cypress/e2e/spec-wc.cy.js
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js

This is a quick fix for https://github.com/RaspberryPiFoundation/editor-ui/issues/1044.
We've been seeing quite a few [`Faraday::Unauthorized` exceptions reported by Sentry in Editor API][1]. These errors are being caused by expired access tokens being sent in the requests from the web component.
This can happen if a user is logged in and is viewing a non-public project, but they close their browser and return to the project some time (1 hour?) later when their access token has expired. In this scenario the project will not load, because of the exception and the user will see the "Loading" text instead of the editor.
This commit prevents the web component from using an expired access token in `WebComponentLoader` and should thus avoid the exeptions we've been seeing.
However, it's not …

Quick fix for expired access token problem in web component

---

CHANGELOG.md
cypress/e2e/spec-wc.cy.js
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js

This reverts the changes in #1046.
The problem that it was addressing has now been more effectively addressed in RaspberryPiFoundation/editor-api#337.

Revert: Quick fix for expired access token problem in web component

---

CHANGELOG.md
src/web-component.js

Fixes an error caused by attempting to register the web component multiple times ⤵️

Only register web component once

---

.env.webcomponent.example
CHANGELOG.md
src/components/EmbeddedViewer/__snapshots__/EmbeddedViewer.test.js.snap
src/components/ExternalFiles/ExternalFiles.jsx
webpack.component.config.js

Fix:
- add external files to document body so it renders outside the shadow DOM
Why:
- Skulpt picks up files by adding them to the DOM (see https://github.com/skulpt/skulpt/issues/854#issuecomment-486135840)
- this doesn't play nice with the shadow DOM and Skulpt doesn't recoginse files like `.txt` and `.csv`
- `createPortal` enables us to pick a common host element (i.e. `body`) and attach the required div's there

Fix Skulpt External Files

---

.github/workflows/ci-cd.yml
CHANGELOG.md

Accidentally broken the `main` branch deployment used for staging during a little innovation tidy up

Fix deploy main branch CI

---

CHANGELOG.md
public/shims/processing/p5/p5-shim.js
public/shims/processing/py5/py5-shim.js
src/components/Editor/Runners/PythonRunner/VisualOutputPane.jsx
src/components/Editor/Runners/PythonRunner/VisualOutputPane.test.js

Currently p5 related projects using the web component in the projects site are broken
- Integrated editor projects in the projects site that utilise p5 error on run (see https://projects.raspberrypi.org/en/projects/editor-target-practice/editor)
- The same editor projects loaded directly in on the editor domain run fine (see https://editor.raspberrypi.org/en/projects/editor-target-practice-starter)
- When break points are added its clear the aspects loaded into p5 via the p5-shim aren't loaded (or in scope at least) when ran in the projects-ui code (i.e. http://localhost:3001/en/projects/editor-rocket-launch/editor) and errors are seen
- Aspects can be initialised in different places or altered slightly so there's less of a dependency on the order they're ran (i.e. removing `Sk.p5.sketch` …

Investigate broken projects site editor web component

---

CHANGELOG.md
README.md
cypress/e2e/spec-html.cy.js
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx
src/components/Editor/Runners/HtmlRunner/HtmlRunner.test.js

Accessing localstorage (eg. `localstorage.getItem('authKey')`) is a potential security risk when running code that has been shared between individuals / is untrusted.
This change overrides the specific localstorage method / key access and provides feedback in the browser console.
Access to localstorage is not entirely blocked as it is used in many projects / resources eg. [Share Your World](https://projects.raspberrypi.org/en/projects/share-your-world) (https://github.com/search?q=repo%3Araspberrypilearning%2Fshare-your-world%20localstorage&type=code)
For more context, see: https://github.com/RaspberryPiFoundation/documentation/pull/112/files
***
The change can be tested by creating a new HTML project in the editor, inputting the following and inspecting the console for the output:
``` …
```

Disable specific localstorage access at runtime

---

CHANGELOG.md
cypress/e2e/spec-html.cy.js
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx
src/components/Editor/Runners/HtmlRunner/HtmlRunner.test.js

Access to all localstorage keys starting with `oidc.` will be disallowed when executing code.
Improves: https://github.com/RaspberryPiFoundation/editor-ui/pull/1079

Broaden scope of localstorage keys disallowed

---

CHANGELOG.md
src/components/WebComponentProject/WebComponentProject.jsx

Small fix to stop web component switching to the pre-set split/tabbed view on every code run
I thought this was related to the `pyodide` switch but it turned out not to be - this is actually an annoying bug that is live on production 😅

Fix web component tabbed view

---

CHANGELOG.md
cypress/e2e/spec-wc-pyodide.cy.js
src/PyodideWorker.js
src/components/Editor/Runners/PythonRunner/PyodideRunner/PyodideWorker.test.js

Refactored the `PyodideWorker` so that `pyodide` is not completely reloaded on each code run, but rather the globals representing user-defined variables and user-imported modules are cleared. This allows the modules that have already been loaded into `pyodide` to be cached, massively reducing the latency on subsequent code runs.

Cache `pyodide` modules

---

CHANGELOG.md
package.json
src/PyodideWorker.js

Due to there not being an `after` in the pyodide vendored package the stop button was disabled

Fix stopping py-enigma code

---

CHANGELOG.md
package.json
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js
src/hooks/useProjectPersistence.js
src/hooks/useProjectPersistence.test.js

Initial attempt at a fix for auto loading remixes when we explicitly don't want to to avoid editor projects remixing, loading the remix then causing a url changed based off the load rather than remix response

Check loadRemixDisabled

---

.devcontainer/devcontainer.json
CHANGELOG.md
src/components/Editor/Runners/PythonRunner/SkulptRunner/SkulptRunner.jsx

Reported that when running p5 code more than once the runner breaks and errors.
This remove setting visualOutput to false and uses initial state and rerenders to set the correct visual output behaviour.
This is still dynamic and works well when adding code that requires visualisation as well as always showing for the sense hat model

Fix p5 run errors

---

CHANGELOG.md
src/assets/themes/editorDarkTheme.js

- Fixed the selector specificity for selected text in the editor
- Toned down the match highlighting

Fix dark mode selection highlighting

---

CHANGELOG.md
package.json
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx
src/components/Editor/Runners/HtmlRunner/HtmlRunner.test.js
yarn.lock

- `HtmlRunner` now looks for media in `editor.project.videos` and `editor.project.audio` as well as `editor.project.image_list`
- Upgraded React Testing Library to reduce test warnings

HTML audio video support

---

CHANGELOG.md
src/assets/stylesheets/Instructions.scss
src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.jsx
src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.test.js
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js

closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/418

Instructions syntax highlighting for CEfE

---

CHANGELOG.md
src/components/WebComponentProject/WebComponentProject.jsx
src/components/WebComponentProject/WebComponentProject.test.js

This is fixing a bug where the user deletes everything in the instructions box and it suddenly switches back to the empty instructions state. This was caused by the fact that an empty string is `falsy` in Javascript, so when the instructions content was deleted we would get `projectInstructions = ""` which resulted in the instructions being deleted.

Fixing instructions state when set to an empty string

---

CHANGELOG.md
src/components/Menus/Sidebar/SidebarBar.jsx
src/components/Menus/Sidebar/SidebarBar.test.js

[closes](https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/443)
I found that `const option = instructions ? "instructions" : "file";` was always being set to true because it was receiving an empty array

Check instructions length before setting option value

---

CHANGELOG.md
src/PyodideWorker.js
src/components/Editor/Runners/PythonRunner/PyodideRunner/PyodideRunner.jsx
src/components/Editor/Runners/PythonRunner/PyodideRunner/PyodideRunner.test.js

- Fixed the mode on the `pyodide` side - it was always using `w` rather than the mode provided in the code
- Fixed the file write append mode on the frontend - it was incorrectly adding a newline character before anything was appended.

Fixing the append file write mode

---

CHANGELOG.md
src/redux/EditorSlice.js

closes https://github.com/RaspberryPiFoundation/editor-ui/issues/1202

Add runnerBeingLoaded logic

---

CHANGELOG.md
src/assets/stylesheets/ProjectBar.scss
src/assets/stylesheets/SaveStatus.scss

- Removed fixed ProjectBar height to allow button it to grow if needed
- Centre aligned buttons
- Tweak save status space for better aesthetics when wrapping (and in general)
**English**
https://github.com/user-attachments/assets/e0539516-ccaf-4281-8ce6-c9b348c11237
**German / Longer text (logged out)**
https://github.com/user-attachments/assets/825e46dc-4d72-4c42-b289-05fd2cc472b3
**German / Longer text (logged in)**
https://github.com/user-attachments/assets/002d7a18-fc24-4241-b222-1d47b3f0e868
Did consider changing the text box to fill available space but decided against it.

fix: login to save button overflow

---

CHANGELOG.md
public/translations/en.json
public/translations/xx-XX.json
src/assets/markdown/demoInstructions.md
src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.jsx
src/utils/populateMarkdownTemplate.js
src/utils/populateMarkdownTemplate.test.js

- Converted `demoInstructions.md` into a tetmplate that references the keys from the translation files
- Added a helper to replace the keys in the template with the correct translations
- Applied this to the demo instructions when they are set as the project instructions when the user clicks "Add instructions"

Translate demo instructions

---

CHANGELOG.md
src/assets/stylesheets/EditorPanel.scss

closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/720

Show horizontal scrollbar in editor when needed

---

CHANGELOG.md
public/translations/en.json
public/translations/xx-XX.json

closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/808
- Updated `imagePanel.gallery` to sentence case
- Updated `imageUploadButton.uploadImage` to sentence case
- Removed unused string (I found while searching)
Unused string:

fix: image gallery capitalisation

---

CHANGELOG.md
src/assets/themes/editorDarkTheme.js
src/assets/themes/editorLightTheme.js

closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/721

Set selectionMatch to be transparent

---

CHANGELOG.md
README.md
package.json
src/containers/WebComponentLoader.jsx
src/containers/WebComponentLoader.test.js
src/utils/i18n.js
src/web-component.js
yarn.lock

Switches to determining the language from an attribute rather than detecting through `i81n`. This maintains independence from the setup of the host page whilst allowing the web component to be consistent with the host in its choice of language.
closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/883

Add locale attribute instead of detecting language

---

README.md

This pull request updates the project documentation to clarify the recommended way to install dependencies. 
It adds instructions to use Yarn 3 instead of npm due to compatibility issues with some legacy packages.
Documentation improvements:
* Added a new section in `README.md` explaining that dependencies should be installed using Yarn 3, and warning that `npm install` may fail because of strict peer-dependency resolution.

Update README.md to include how to initial install
