CHANGELOG.md
package.json

- Plausbile event tracking for login, remix, save and code run (#250)
- Message prompting users to login or save if they make non-autosaved changes (#291)
- Unit tests for the autosave trigger (#291)
- Project not found and access denied modals shown on project loading error (#298)
- Styling for small buttons (#303)
- Project page header and styling (#314)
- Ability to open and focus files from the left hand file pane (#301)
- Ability to close file tabs (#301)
- Validation to prevent file names containing spaces (#301)
- Bump terser from 4.8.0 to 4.8.1 (#143)
- Updated buttons and tabs styling (#296)
- Updated icons (#296)
- Bump engine.io from 6.2.0 to 6.2.1 (#272)
- Increased clickable area for tabs (#299)
- Bump decode-uri-component from 0.2.0 to 0.2.2 (#295)
- File tab bar scrolls …

Release v0.10.0

---

.gitattributes
CHANGELOG.md

This should reduce the amount of PR conflict

Add merge=union for the CHANGELOG file

---

CHANGELOG.md
src/components/Editor/EditorSlice.js
src/utils/defaultProjects.js

- Removed reference to file index to fix new project creation and saving a new file

Remove reference to file index

---

CHANGELOG.md
src/components/Editor/Output/Output.js

- Tiny fix to use `HtmlRunner` for `html` projects so we can see what changes need to be made

Fix wrong runner bug

---

CHANGELOG.md
src/utils/userManager.js

Related to https://github.com/RaspberryPiFoundation/digital-editor/issues/77

Allow u13s accounts

---

.devcontainer/devcontainer.json
CHANGELOG.md
Dockerfile

Add dev container support

---

CHANGELOG.md
package.json

Release v0.16.0

---

CHANGELOG.md
src/tabs.scss

closes https://raspberrypifoundation.slack.com/archives/C13FSSVDG/p1689004304702779

Allow output text to be scrollable if overflow-y

---

src/components/Menus/Sidebar/Sidebar.js

Make sure only one item is spliced from the array

Fix-menu-splice

---

.github/workflows/ci-cd.yml
.github/workflows/deploy.yml
.npmrc

Get our CI working with a private package

Deploy design-system-react

---

CHANGELOG.md
package.json

- Sidebar settings (#585)
- Sidebar info (#566)
- Add Projects Panel to sidebar (#564)
- Minor fixes to the sidebar layout (#602)
- Fixed text wrap in the files section of the Sidebar (#596)
- LandingPage and ProjectBar's Save buttons use design-system-react (#579)
- Update colors for buttons (#579)

New release

---

CHANGELOG.md
src/colours.scss
src/components/Menus/Sidebar/ProjectsPanel/ProjectsPanel.scss
src/components/SaveButton/SaveButton.js
src/components/SaveStatus/SaveStatus.js
src/components/SaveStatus/SaveStatus.scss

Closing https://github.com/RaspberryPiFoundation/editor-ui/issues/626

Sidebar - Save button fix

---

CHANGELOG.md
package.json
yarn.lock

Normal version bumps for release and minor change to yarn lock on install

Release v0.19.0

---

CHANGELOG.md
package.json

Version bumps for release of bug fix

Release v0.19.2

---

CHANGELOG.md
package.json

CHANGELOG and package.json changes for release

Release v0.19.3

---

.npmrc
CHANGELOG.md
Dockerfile
docker-compose.yml
package.json
src/components/DesignSystemButton/DesignSystemButton.jsx
yarn.lock

Remove need to pull private package

design-system-react public dependancy

---

CHANGELOG.md
Dockerfile
docker-compose.yml
package.json
yarn.lock

Couple of minor things:
- inclusion of `yarn` in Dockerfile
- removal of npmrc setup in docker-compose
- small bump to design-system-react

Fix local setup

---

CHANGELOG.md
src/components/Editor/DraggableTabs/DraggableTab.jsx
src/components/Editor/EditorInput/EditorInput.test.js
src/components/Editor/Project/Project.jsx
src/components/Menus/Sidebar/SidebarPanel.jsx

Includes:
- Removing resizable handle errors
- Increasing sidebar width for instructions

Minor web component improvements

---

CHANGELOG.md
src/assets/stylesheets/Instructions.scss

Fix gap between different instruction blocks
Fix multi-line output block

Instructions styling fixes

---

src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.jsx

InstructionsPanel has a random debugger

---

CHANGELOG.md
package.json

Project site integration changes

Release v0.21.0

---

CHANGELOG.md
src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx

fix preview link

---

CHANGELOG.md
src/assets/stylesheets/Tabs.scss
src/components/LandingPage/LandingPage.jsx
src/components/Menus/Sidebar/SettingsPanel/ThemeToggle/ThemeToggle.jsx
src/components/Menus/Sidebar/SettingsPanel/ThemeToggle/ThemeToggle.test.js
src/containers/WebComponentLoader.jsx
src/events/WebComponentCustomEvents.js

- Fires custom event when the theme changes, so the web component's host page can update the theme straight away.
- Removes rogue semi colon from web component loading state

Fix web component theming

---

CHANGELOG.md
package.json

- Wrap `WebComponentLoader` in a `BrowserRouter` to fix routing issues (#1035)

Release 0-25-1

---

CHANGELOG.md
package.json

- Quick fix for expired access token problem in web component (#1046)

Release v0.25.3

---

CHANGELOG.md
package.json

- Revert: Quick fix for expired access token problem in web component (#1048)

Release v0.25.4

---

CHANGELOG.md
src/components/Editor/Runners/PythonRunner/VisualOutputPane.jsx

closes https://github.com/RaspberryPiFoundation/editor-standalone/issues/388

Fix bug where the turtle canvas couldn't be found

---

CHANGELOG.md
src/components/Editor/EditorInput/EditorInput.jsx

Fixes - https://raspberrypifoundation.slack.com/archives/C022FDFRM7B/p1730800544670889

EditorInput - remove auto scroll on content change

---

.tool-versions
CHANGELOG.md
Dockerfile
docker-compose.yml

Ready for review
- Update docker config to match standalone
- run yarn install and yarn start on container start

Updates docker config to match standalone, and run yarn install and yarn start on container start

---

CHANGELOG.md
package.json

- Log in to save and log in now preserve the cache (#1137)

release v0.28.13

---

CHANGELOG.md
src/components/DownloadButton/DownloadButton.jsx
src/components/DownloadButton/DownloadButton.test.js
src/components/Modals/NewFileModal.test.js
src/components/Modals/RenameFileModal.test.js
src/utils/componentNameValidation.js
src/utils/i18n.js

- Includes instructions in the project download if there are any
- Adds a list of reserved file names which includes `INSTRUCTIONS.md` to prevent clashes
Closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/374

Downloading the instructions

---

CHANGELOG.md
README.md
src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.jsx
src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.test.js
src/components/Menus/Sidebar/InstructionsPanel/ProgressBar/ProgressBar.jsx
src/components/Menus/Sidebar/InstructionsPanel/ProgressBar/ProgressBar.test.js
src/components/WebComponentProject/WebComponentProject.jsx
src/containers/WebComponentLoader.jsx
src/redux/EditorSlice.js
src/web-component.js

* unblocks us
* merging into feature branch

new prop for editable instructions

---

CHANGELOG.md
package.json
src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.jsx
src/components/Menus/Sidebar/InstructionsPanel/InstructionsPanel.test.js
src/components/WebComponentProject/WebComponentProject.jsx
src/redux/EditorSlice.js
yarn.lock

* Autosaves instructions 
* also renders markdown instructions

Autosave instructions 

---

CHANGELOG.md
src/assets/stylesheets/Instructions.scss
src/assets/stylesheets/InternalStyles.scss

fix dark mode colours

---

CHANGELOG.md
src/utils/i18n.js

closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/413

Copy change: Project steps to Project instructions

---

CHANGELOG.md
src/assets/stylesheets/Instructions.scss

closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/414

Fixing padding for first line of code block

---

CHANGELOG.md
src/assets/stylesheets/Instructions.scss

closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/416

Fix contrast on dark mode instructions code block

---

CHANGELOG.md
package.json

* Support output tabs in pyodide by @loiswells97 in https://github.com/RaspberryPiFoundation/editor-ui/pull/1157
* Downloading the instructions by @loiswells97 in https://github.com/RaspberryPiFoundation/editor-ui/pull/1160
* Hack open function to write files in main thread by @loiswells97 in https://github.com/RaspberryPiFoundation/editor-ui/pull/1146
* Try pinning previous ubuntu version to avoid cloudflare issue by @danhalson in https://github.com/RaspberryPiFoundation/editor-ui/pull/1178
* Integration: Save / Login functionality not as expected by @create-issue-branch in https://github.com/RaspberryPiFoundation/editor-ui/pull/1162
* HTML audio video support by @loiswells97 in https://github.com/RaspberryPiFoundation/editor-ui/pull/1179
* Feat/editable instructions by @loiswells97 in …

Release v0.29.0

---

CHANGELOG.md
src/assets/stylesheets/Sidebar.scss

Related To https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/419

fix sidebar styling on mobile
